### PR TITLE
Update runtime to 6.4

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by Deevad** [comment]
Thanks for the update! I tried what said the message of the bot to test it, but it return a 404 error:
```
~ »»» flatpak install --user https://dl.flathub.org/build-repo/7013/org.beeref.BeeRef.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/7013/org.beeref.BeeRef.flatpakref: Server returned status 404
```

**Comment by JakobDev** [comment]
I think, the test builds are deleted after a certain time. Let's rebuild.

bot, build

**Comment by Deevad** [comment]
Thank you @JakobDev ! 

Unfortunately, the icon doesn't work. Here is what I have in a terminal. 

```
~ »»» flatpak install --user https://dl.flathub.org/build-repo/8176/org.beeref.BeeRef.flatpakref

org.beeref.BeeRef permissions:
    ipc      network      fallback-x11     wayland     x11     dri     file access [1]     dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar


        ID                         Branch          Op          Remote                 Download
 1. [✓] org.beeref.BeeRef          test            i           beeref-origin          70,5 MB / 70,2 MB

Installation complete.
~ »»» flatpak run org.beeref.BeeRef
INFO __main__: Starting BeeRef version 0.2.0
INFO __main__: Using settings: /home/deevad/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.ini
INFO __main__: Logging to: /home/deevad/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.log
CRITICAL __main__: Unhandled exception
Traceback (most recent call last):
  File "beeref/__main__.py", line 116, in <module>
  File "beeref/__main__.py", line 102, in main
  File "beeref/__main__.py", line 53, in __init__
  File "beeref/assets/__init__.py", line 34, in __new__
  File "beeref/assets/__init__.py", line 41, in on_new
  File "beeref/assets/__init__.py", line 54, in cursor_from_image
TypeError: arguments did not match any overloaded call:
  QCursor(): too many arguments
  QCursor(bitmap: QBitmap, mask: QBitmap, hotX: int = -1, hotY: int = -1): argument 1 has unexpected type 'QPixmap'
  QCursor(pixmap: QPixmap, hotX: int = -1, hotY: int = -1): argument 2 has unexpected type 'float'
  QCursor(cursor: Union[QCursor, Qt.CursorShape]): argument 1 has unexpected type 'QPixmap'
  QCursor(variant: Any): too many arguments
[3] Failed to execute script '__main__' due to unhandled exception!
Exception ignored in: <function BeeRefMainWindow.__del__ at 0x7fe08fe1d480>
Traceback (most recent call last):
  File "beeref/__main__.py", line 60, in __del__
AttributeError: view
~ »»» 

```

**Comment by JakobDev** [comment]
The error say what the Problem is:

>   QCursor(pixmap: QPixmap, hotX: int = -1, hotY: int = -1): argument 2 has unexpected type 'float'

Changing [this line](https://github.com/rbreu/beeref/blob/c308c08a07a6bce0ee1ece487f924811f1e56053/beeref/assets/__init__.py#L54) to
```python
return QtGui.QCursor(pixmap, int(hotspot[0]/scaling), int(hotspot[1]/scaling))
```
should fix the problem.

**Comment by juankprada** [comment]
is there any update on this? flatpak version is still not working

**Comment by dginovker** [comment]
Looks like upstream fixed this today; when BeeRef 3.1 comes out, this will be mergable. 

@juankprada Are you unable to install the Flatpak version at all? It should only be giving a warning

**Comment by juankprada** [comment]
I am currently able to install and use BeeRef from flatpak just fine. it looks like the error is fixed. Thanks for the support!

**Comment by dginovker** [comment]
Seems good in my limited testing. Thanks!

**Pull request merged**
