### PR TITLE
Use upstream appdata

### PR DESCRIPTION
**Pull request by rafaelmardojai**
Upstream maintains an AppStream metadata file.

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
bot, build org.beeref.BeeRef

**Comment by rafaelmardojai** [comment]
Requires https://github.com/rbreu/beeref/pull/110

**Comment by dginovker** [comment]
@rafaelmardojai I'm ready to merge when you mark as ready :+1:

**Comment by dginovker** [comment]
(Was fixing history I messed up)

**Pull request merged**
